name: release
on:
  schedule:
  - cron: '0 0 * * *' # midnight UTC

  push:
    branches:
    - release
    - arm-build

jobs:
  dist:
    name: dist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      RUSTFLAGS: -D warnings -C linker=rust-lld -C linker-flavor=ld.lld
      CARGO_INCREMENTAL: 0
      RUSTUP_MAX_RETRIES: 10
      CARGO_NET_RETRY: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # We need to disable the existing toolchain to avoid updating rust-docs
    # which takes a long time. The fastest way to do this is to rename the
    # existing folder, as deleting it takes about as much time as not doing
    # anything and just updating rust-docs.
    - name: Rename existing rust toolchain (Windows)
      if: matrix.os == 'windows-latest'
      run: Rename-Item C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc.old

    - name: Install Rust toolchain
      uses: qmx/toolchain@multi-target
      with:
        toolchain: stable
        profile: minimal
        targets: x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf
        override: true

    - name: Install Nodejs
      if: matrix.os == 'ubuntu-latest'
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Dist
      if: github.event_name == 'push'
      run: cargo xtask dist

    - name: Dist (armv7)
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      run: cargo build -p rust-analyzer --target armv7-unknown-linux-musleabihf

    - name: Dist
      if: github.event_name != 'push'
      run: cargo xtask dist --nightly

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-${{ matrix.os }}
        path: ./dist


  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: ['dist']
    steps:
    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: echo "::set-env name=TAG::$(date --iso --utc)"
      if: github.event_name == 'push'
    - run: echo "::set-env name=TAG::nightly"
      if: github.event_name == 'schedule'
    - run: 'echo "TAG: $TAG"'

    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v1
      with:
        name: dist-macos-latest
        path: dist
    - uses: actions/download-artifact@v1
      with:
        name: dist-ubuntu-latest
        path: dist
    - uses: actions/download-artifact@v1
      with:
        name: dist-windows-latest
        path: dist
    - run: ls -all ./dist

    - name: Publish Release
      uses: ./.github/actions/github-release
      with:
        files: "dist/*"
        name: ${{ env.TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: npm ci
      working-directory: ./editors/code

    - name: Publish Extension
      if: github.event_name == 'push'
      working-directory: ./editors/code
      # token from https://dev.azure.com/rust-analyzer/
      run: npx vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }} --packagePath ../../dist/rust-analyzer.vsix
